import Head from "next/head";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <Layout title="Home">
      <div>
        <Head>
          <title>NextShop</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="bg-slate-100 p-2">
          <h1 className="text-3xl font-bold">NextShop</h1>
          <p>JinUk Lee</p>
          <p>- TailwindCSS</p>
          <p>- MongoDB</p>
        </div>
      </div>
    </Layout>
  );
}
